### ISSUE TITLE
Add Support for Span instead of BinaryWriter / Reader

### ISSUE THREAD

**Issue by susch19** [NoobDevTv/NonSucking.Framework.Extension#12]
Currently only BinaryReader and Writer are supported, but Span should be supported aswell.

- [ ] Support for Span in Serialize
- [ ] Span for Deserialize

Maybe also support Streams as a more general approach instead of reader and writer

**Comment by jvbsl** [comment]
https://github.com/NoobDevTv/NonSucking.Framework.Extension/pull/53
through direct readers and writers a ref struct implementing methods of INoosonBinaryReader/Writer(interface implementation on ref structs not possible, just implement the methods themselves) possible
